# fly.toml app configuration file for nassarapplication
# See https://fly.io/docs/reference/configuration/ for details

app = "nassarapplication"
primary_region = "cdg"   # Paris, closest stable region to Algeria

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
