# fly.toml app configuration file for nassarap
# See https://fly.io/docs/reference/configuration/ for details

app = "nassarap"
primary_region = "iad"   # your app is deployed in IAD region

[build]
  dockerfile = "Dockerfile"

[[mounts]]
  source = "data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
